"""
classify.py — Loads the trained model once at startup and exposes classify_image().

The model is trained with MobileNetV2 at 160×160.  Class labels are loaded from
saved_model/class_names.json (generated by fine_tune_model.py).
"""

import os
import json
import numpy as np
import tensorflow as tf
from PIL import Image, ImageOps

# ==============================
# LOAD MODEL ONCE AT STARTUP
# ==============================

MODEL_PATH  = "saved_model/gender_classification_model.keras"
LABELS_PATH = "saved_model/class_names.json"

if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(
        f"Model not found at '{MODEL_PATH}'. Run fine_tune_model.py first."
    )

model = tf.keras.models.load_model(MODEL_PATH, compile=False)

# Load labels: {"Female": 0, "Male": 1}  →  invert to {0: "Female", 1: "Male"}
if os.path.exists(LABELS_PATH):
    with open(LABELS_PATH, "r") as f:
        class_indices = json.load(f)
    labels = {v: k for k, v in class_indices.items()}
else:
    labels = {0: "Female", 1: "Male"}

# Derive image size from the model's input shape
_input_shape = model.input_shape  # (None, H, W, C)
IMG_SIZE = (_input_shape[1], _input_shape[2])

print(f"[classify] Model loaded | input size: {IMG_SIZE} | classes: {labels}")


def _preprocess(img_path: str) -> np.ndarray:
    """
    Load and preprocess an image for inference.

    Steps:
      1. Open and convert to RGB (handles RGBA/grayscale webcam captures)
      2. Auto-contrast — stretches the histogram to fill 0-255, which
         normalises the colour balance difference between webcam and
         training images (studio-lit CelebA photos).
      3. Resize to model input size with high-quality resampling.
      4. Normalise to [0, 1] and add batch dimension.
    """
    img = Image.open(img_path).convert("RGB")

    # Auto-contrast: stretches each channel independently so that the
    # darkest pixel becomes 0 and the brightest becomes 255.
    # This reduces the lighting/colour-temperature gap between webcam
    # captures and the training distribution.
    img = ImageOps.autocontrast(img, cutoff=1)

    img = img.resize(IMG_SIZE, Image.LANCZOS)
    arr = np.array(img, dtype=np.float32) / 255.0
    return np.expand_dims(arr, axis=0)


def classify_image(img_path: str) -> dict:
    """
    Classify a face image as Male or Female.

    Args:
        img_path: Path to the image file.

    Returns:
        dict with keys 'label' (str), 'confidence' (float, 0–100),
        'probabilities' (dict), and 'inference_ms' (float).
        On error, returns dict with key 'error' (str).
    """
    import time

    try:
        img_array = _preprocess(img_path)

        start_time = time.perf_counter()
        prediction = model.predict(img_array, verbose=0)
        inference_ms = (time.perf_counter() - start_time) * 1000

        predicted_class = int(np.argmax(prediction[0]))
        confidence      = float(prediction[0][predicted_class])

        # Build probabilities dict for all classes
        probabilities = {
            labels[i]: round(float(prediction[0][i]) * 100, 2)
            for i in range(len(prediction[0]))
        }

        return {
            "label":         labels[predicted_class],
            "confidence":    round(confidence * 100, 2),
            "probabilities": probabilities,
            "inference_ms":  round(inference_ms, 1),
        }
    except Exception as e:
        return {"error": str(e)}
